---
# tasks file for docker-role
- name: "FROM ROLE: Installing git using apk module"
  apk:
    name: git
    state: present

- name: "FROM ROLE: Installing Nano using apk module"
  apk:
    name: nano
    state: present
